# Generated by Django 4.1.1 on 2022-09-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=120, verbose_name='Carusel name 1')),
                ('name2', models.CharField(max_length=120, verbose_name='Carusel name 2')),
                ('name3', models.CharField(blank=True, max_length=120, verbose_name='Carusel name 3')),
                ('img1', models.ImageField(upload_to='media', verbose_name='Carusel image 1')),
                ('img2', models.ImageField(upload_to='media', verbose_name='Carusel image 2')),
            ],
            options={
                'verbose_name': 'HomeCarusel',
                'verbose_name_plural': 'HomeCarusels',
            },
        ),
    ]
