# Generated by Django 4.1.1 on 2022-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecarusel',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='homecarusel',
            name='img2',
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Carusel image'),
        ),
    ]
