# Generated by Django 4.1.1 on 2022-09-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homecarusel1_homecarusel2_homecarusel3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarusel1',
            name='name1',
            field=models.CharField(default=1, max_length=120, verbose_name='Carusel1 name 1'),
            preserve_default=False,
        ),
    ]
