# Generated by Django 4.1.1 on 2022-09-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_homecarusel1_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarusel1',
            name='img',
            field=models.ImageField(upload_to='media', verbose_name='Carusel1 image'),
        ),
        migrations.AlterField(
            model_name='homecarusel1',
            name='name2',
            field=models.CharField(max_length=120, verbose_name='Carusel1 name 2'),
        ),
        migrations.AlterField(
            model_name='homecarusel2',
            name='img',
            field=models.ImageField(upload_to='media', verbose_name='Carusel2 image'),
        ),
        migrations.AlterField(
            model_name='homecarusel2',
            name='name1',
            field=models.CharField(max_length=120, verbose_name='Carusel2 name 1'),
        ),
        migrations.AlterField(
            model_name='homecarusel2',
            name='name2',
            field=models.CharField(max_length=120, verbose_name='Carusel2 name 2'),
        ),
        migrations.AlterField(
            model_name='homecarusel2',
            name='name3',
            field=models.CharField(max_length=120, verbose_name='Carusel2 name 3'),
        ),
        migrations.AlterField(
            model_name='homecarusel3',
            name='img',
            field=models.ImageField(upload_to='media', verbose_name='Carusel3 image'),
        ),
        migrations.AlterField(
            model_name='homecarusel3',
            name='name1',
            field=models.CharField(max_length=120, verbose_name='Carusel3 name 1'),
        ),
        migrations.AlterField(
            model_name='homecarusel3',
            name='name2',
            field=models.CharField(max_length=120, verbose_name='Carusel3 name 2'),
        ),
        migrations.AlterField(
            model_name='homecarusel3',
            name='name3',
            field=models.CharField(max_length=120, verbose_name='Carusel3 name 3'),
        ),
    ]
