# Generated by Django 4.1.1 on 2022-09-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_homecarusel1_img_alter_homecarusel1_name2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=25, verbose_name='AboutUs Title')),
                ('name2', models.CharField(max_length=75, verbose_name='AboutUs name1')),
                ('about', models.TextField(verbose_name='AboutUs about')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUses',
            },
        ),
    ]
