# Generated by Django 4.1.1 on 2022-09-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='ValueCategory name')),
                ('about', models.TextField(verbose_name='ValueCategory about')),
            ],
            options={
                'verbose_name': 'ValueCategory',
                'verbose_name_plural': 'ValueCategories',
            },
        ),
    ]
