# Generated by Django 4.1.1 on 2022-09-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_valuecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuecategory',
            name='about',
        ),
        migrations.CreateModel(
            name='ValueCategorySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='ValueCategorySubcategory')),
                ('valuecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcateg', to='main.valuecategory')),
            ],
            options={
                'verbose_name': 'ValueCategorySubcategory',
                'verbose_name_plural': 'ValueCategorySubcategories',
            },
        ),
    ]
