# Generated by Django 4.1.1 on 2022-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_valuecategory_about_valuecategorysubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='YourNeed name')),
            ],
            options={
                'verbose_name': 'YourNeed',
                'verbose_name_plural': 'YourNeeds',
            },
        ),
    ]
