# Generated by Django 4.1.1 on 2022-09-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='img',
        ),
        migrations.AddField(
            model_name='skill',
            name='img1',
            field=models.ImageField(default=1, upload_to='media', verbose_name='Skill image1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Skill image2'),
        ),
    ]
