# Generated by Django 4.1.1 on 2022-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_skill_img_skill_img1_skill_img2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='ServiceAvatar image')),
            ],
            options={
                'verbose_name': 'ServiceAvatar',
                'verbose_name_plural': 'ServiceAvatars',
            },
        ),
        migrations.RemoveField(
            model_name='skill',
            name='img2',
        ),
    ]
