# Generated by Django 4.1.1 on 2022-09-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_serviceavatar_remove_skill_img2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Skill1 name')),
                ('about', models.TextField(verbose_name='Skill1 about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Skill1 image')),
            ],
            options={
                'verbose_name': 'Skill1',
                'verbose_name_plural': 'Skills1',
            },
        ),
        migrations.CreateModel(
            name='Skill2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Skill2 name')),
                ('about', models.TextField(verbose_name='Skill2 about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Skill2 image')),
            ],
            options={
                'verbose_name': 'Skill2',
                'verbose_name_plural': 'Skills2',
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
