# Generated by Django 4.1.1 on 2022-09-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_skill1_skill2_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=75, verbose_name='ProjectTitle name1')),
                ('name2', models.CharField(max_length=75, verbose_name='ProjectTitle name2')),
            ],
            options={
                'verbose_name': 'ProjectTitle',
                'verbose_name_plural': 'ProjectTitles',
            },
        ),
    ]
