# Generated by Django 4.1.1 on 2022-09-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_projecttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProjectCategory name')),
            ],
            options={
                'verbose_name': 'ProjectCategory',
                'verbose_name_plural': 'ProjectCategories',
            },
        ),
    ]
