# Generated by Django 4.1.1 on 2022-09-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_projectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategorySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, verbose_name='ProjectCategorySubcategory name1')),
                ('name2', models.CharField(max_length=50, verbose_name='ProjectCategorySubcategory name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='ProjectCategorySubcategory image')),
                ('projectcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='main.projectcategory')),
            ],
            options={
                'verbose_name': 'ProjectCategorySubcategory',
                'verbose_name_plural': 'ProjectCategorySubcategories',
            },
        ),
    ]
