# Generated by Django 4.1.1 on 2022-09-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_projectcategorysubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=50, verbose_name='Testimonials name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Testimonials name2')),
                ('name3', models.CharField(max_length=50, verbose_name='Testimonials name3')),
                ('about', models.TextField(verbose_name='Testimonial about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Testimonial image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
