# Generated by Django 4.1.1 on 2022-09-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, verbose_name='NewsLetter name1')),
                ('name2', models.CharField(max_length=50, verbose_name='NewsLetter name2')),
                ('name3', models.CharField(max_length=50, verbose_name='NewsLetter name3')),
                ('name4', models.CharField(max_length=50, verbose_name='NewsLetter name4')),
            ],
            options={
                'verbose_name': 'NewsLetter',
                'verbose_name_plural': 'NewsLetters',
            },
        ),
    ]
