# Generated by Django 4.1.1 on 2022-09-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTitle2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='ProjectTitle2 title1')),
                ('title2', models.CharField(max_length=50, verbose_name='ProjectTitle2 title2')),
            ],
            options={
                'verbose_name': 'ProjectTitle2',
                'verbose_name_plural': 'ProjectTitles2',
            },
        ),
    ]
