# Generated by Django 4.1.1 on 2022-09-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_projecttitle2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='Project2 date')),
                ('about', models.TextField(verbose_name='Project2 about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Project2 image')),
            ],
            options={
                'verbose_name': 'Project2',
                'verbose_name_plural': 'Projects2',
            },
        ),
    ]
