# Generated by Django 4.1.1 on 2022-09-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_project2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeeAllPostButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='SeeAllPostButton name')),
            ],
            options={
                'verbose_name': 'SeeAllPostButton',
                'verbose_name_plural': 'SeeAllPostButtons',
            },
        ),
        migrations.CreateModel(
            name='ViewAllProjectButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ViewAllProjectButton name')),
            ],
            options={
                'verbose_name': 'ViewAllProjectButton',
                'verbose_name_plural': 'ViewAllProjectButtons',
            },
        ),
    ]
