# Generated by Django 4.1.1 on 2022-09-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_seeallpostbutton_viewallprojectbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Addres name')),
            ],
            options={
                'verbose_name': 'Addres',
                'verbose_name_plural': 'Addreses',
            },
        ),
    ]
