# Generated by Django 4.1.1 on 2022-09-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
