# Generated by Django 4.1.1 on 2022-09-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=75, verbose_name='Contact name1')),
                ('name2', models.CharField(max_length=75, verbose_name='Contact name2')),
                ('name3', models.CharField(max_length=75, verbose_name='Contact phone number')),
                ('name4', models.CharField(blank=True, max_length=75, verbose_name='Contact name5')),
                ('img', models.ImageField(upload_to='media', verbose_name='Contact image')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
