# Generated by Django 4.1.1 on 2022-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Contact image'),
        ),
    ]
