# Generated by Django 4.1.1 on 2022-09-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_headerlogo_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerlogo',
            options={'verbose_name': 'HeaderLogo', 'verbose_name_plural': 'HeaderLogos'},
        ),
    ]
