# Generated by Django 4.1.1 on 2022-09-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSetAQuoteButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HeaderSetAQuoteButton name')),
            ],
            options={
                'verbose_name': 'HeaderSetAQuoteButton',
                'verbose_name_plural': 'HeaderSetAQuoteButtons',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name3',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name1',
            field=models.CharField(max_length=50, verbose_name='Contact name1'),
        ),
    ]
