# Generated by Django 4.1.1 on 2022-09-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_headersetaquotebutton_remove_contact_name3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderGetAQuoteButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HeaderGetAQuoteButton name')),
            ],
            options={
                'verbose_name': 'HeaderGetAQuoteButton',
                'verbose_name_plural': 'HeaderGetAQuoteButtons',
            },
        ),
        migrations.DeleteModel(
            name='HeaderSetAQuoteButton',
        ),
    ]
