# Generated by Django 4.1.1 on 2022-09-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_aboutbg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBG',
        ),
    ]
