# Generated by Django 4.1.1 on 2022-09-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_delete_aboutbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='FooterAboutUs name')),
                ('about', models.TextField(verbose_name='FooterAboutUs about')),
                ('img', models.ImageField(upload_to='media', verbose_name='FooterAboutUs image')),
            ],
            options={
                'verbose_name': 'FooterAboutUs',
                'verbose_name_plural': 'FooterAboutUses',
            },
        ),
    ]
