# Generated by Django 4.1.1 on 2022-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_footeraboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='FooterWorkingHour name')),
                ('day', models.CharField(max_length=75, verbose_name='FooterWorkingHour day')),
                ('hour', models.CharField(max_length=50, verbose_name='FooterWorkingHour hour')),
                ('about', models.TextField(verbose_name='FooterWorkingHour about')),
            ],
            options={
                'verbose_name': 'FooterWorkingHour',
                'verbose_name_plural': 'FooterWorkingHours',
            },
        ),
    ]
