# Generated by Django 4.1.1 on 2022-09-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_footerservice_rename_contact_headercontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headercontact',
            options={'verbose_name': 'HeaderContact', 'verbose_name_plural': 'HeaderContacts'},
        ),
    ]
