# Generated by Django 4.1.1 on 2022-09-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_rename_servic_footerservice_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='FooterNavigation name')),
                ('href', models.CharField(max_length=30, verbose_name='FooterNavigation href')),
            ],
            options={
                'verbose_name': 'FooterNavigation',
                'verbose_name_plural': 'FooterNavigations',
            },
        ),
    ]
