# Generated by Django 4.1.1 on 2022-09-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_footernavigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, verbose_name='AboutBG name1')),
                ('name2', models.CharField(max_length=50, verbose_name='AboutBG name2')),
                ('name3', models.CharField(max_length=50, verbose_name='AboutBG name3')),
                ('name4', models.CharField(max_length=50, verbose_name='AboutBG name4')),
                ('img', models.ImageField(upload_to='media', verbose_name='AboutBG image')),
            ],
            options={
                'verbose_name': 'AboutBG',
                'verbose_name_plural': 'AboutBGs',
            },
        ),
    ]
