# Generated by Django 4.1.1 on 2022-09-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_aboutbg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutbg',
            name='name4',
        ),
    ]
