# Generated by Django 4.1.1 on 2022-09-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_aboutbg_name4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutbg',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='aboutbg',
            name='name3',
        ),
    ]
