# Generated by Django 4.1.1 on 2022-09-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_aboutbg_name2_remove_aboutbg_name3'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutbg',
            name='name2',
            field=models.CharField(default=1, max_length=50, verbose_name='AboutBG name2'),
            preserve_default=False,
        ),
    ]
