# Generated by Django 4.1.1 on 2022-09-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_aboutbg_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbg',
            name='name1',
            field=models.CharField(blank=True, max_length=50, verbose_name='AboutBG name1'),
        ),
    ]
