# Generated by Django 4.1.1 on 2022-09-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_aboutbg_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutWhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='AboutWhoWeAre title')),
                ('about1', models.TextField(verbose_name='AboutWhoWeAre about1')),
                ('about2', models.TextField(verbose_name='AboutWhoWeAre about2')),
                ('about3', models.TextField(verbose_name='AboutWhoWeAre about3')),
            ],
            options={
                'verbose_name': 'AboutWhoWeAre',
                'verbose_name_plural': 'AboutWhoWeAres',
            },
        ),
    ]
