# Generated by Django 4.1.1 on 2022-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_aboutwhoweare'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='AboutPageSlider title')),
                ('img', models.ImageField(upload_to='media', verbose_name='AboutPageSlider image')),
            ],
            options={
                'verbose_name': 'AboutWhoWeAre',
                'verbose_name_plural': 'AboutWhoWeAres',
            },
        ),
    ]
