# Generated by Django 4.1.1 on 2022-09-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_aboutpageslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Fact num')),
                ('name', models.CharField(max_length=75, verbose_name='Fact name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Fact image')),
            ],
            options={
                'verbose_name': 'Fact',
                'verbose_name_plural': 'Facts',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpageslider',
            options={'verbose_name': 'AboutPageSlider', 'verbose_name_plural': 'AboutPageSliders'},
        ),
    ]
