# Generated by Django 4.1.1 on 2022-09-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_aboutfact_alter_aboutpageslider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutfact',
            options={'verbose_name': 'AboutFact', 'verbose_name_plural': 'AboutFacts'},
        ),
    ]
