# Generated by Django 4.1.1 on 2022-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_aboutteamtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, verbose_name='AboutTeam name1')),
                ('name2', models.CharField(max_length=50, verbose_name='AboutTeam name2')),
                ('about', models.TextField(verbose_name='AboutTeam about')),
                ('img', models.ImageField(upload_to='media', verbose_name='AboutTeam image')),
            ],
            options={
                'verbose_name': 'AboutTeam',
                'verbose_name_plural': 'AboutTeams',
            },
        ),
    ]
