# Generated by Django 4.1.1 on 2022-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_teamteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TeamTitle title')),
            ],
            options={
                'verbose_name': 'TeamTitle',
                'verbose_name_plural': 'TeamTitles',
            },
        ),
        migrations.RemoveField(
            model_name='teamteam',
            name='title',
        ),
    ]
