# Generated by Django 4.1.1 on 2022-09-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_teamtitle_remove_teamteam_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=50, verbose_name='TestimonialsBG name1')),
                ('name2', models.CharField(max_length=50, verbose_name='TestimonialsBG name2')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='TestimonialsBG image')),
            ],
            options={
                'verbose_name': 'TestimonialsBG',
                'verbose_name_plural': 'TestimonialsBGs',
            },
        ),
    ]
