# Generated by Django 4.1.1 on 2022-09-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_testimonialsbg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestimonialsBG',
            new_name='TestimonialBG',
        ),
        migrations.AlterModelOptions(
            name='testimonialbg',
            options={'verbose_name': 'TestimonialsBG', 'verbose_name_plural': 'TestimonialBGs'},
        ),
    ]
