# Generated by Django 4.1.1 on 2022-09-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_rename_testimonialsbg_testimonialbg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialQuoteTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TestimonialTitle title')),
            ],
            options={
                'verbose_name': 'TestimonialTitle',
                'verbose_name_plural': 'TestimonialTitles',
            },
        ),
    ]
