# Generated by Django 4.1.1 on 2022-09-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_faqbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCatTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=75, verbose_name='FaqCatTitle title1')),
                ('title2', models.CharField(max_length=75, verbose_name='FaqCatTitle title2')),
            ],
            options={
                'verbose_name': 'FaqCatTitle',
                'verbose_name_plural': 'FaqCatTitles',
            },
        ),
    ]
