# Generated by Django 4.1.1 on 2022-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_faqcat_faqcatsubcat2_faqcatsubcat1'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCatTitle1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=75, verbose_name='FaqCatTitle1 title1')),
                ('title2', models.CharField(max_length=75, verbose_name='FaqCatTitle1 title2')),
            ],
            options={
                'verbose_name': 'FaqCatTitle1',
                'verbose_name_plural': 'FaqCatTitles1',
            },
        ),
        migrations.DeleteModel(
            name='FaqCatTitle',
        ),
    ]
