# Generated by Django 4.1.1 on 2022-09-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_faqcattitle1_delete_faqcattitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqcattitle1',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='faqcattitle1',
            name='title2',
        ),
        migrations.AddField(
            model_name='faqcattitle1',
            name='title',
            field=models.CharField(default=1, max_length=75, verbose_name='FaqCatTitle title1'),
            preserve_default=False,
        ),
    ]
