# Generated by Django 4.1.1 on 2022-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_remove_faqcattitle1_title1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCatTitle2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='FaqCatTitle title2')),
            ],
            options={
                'verbose_name': 'FaqCatTitle2',
                'verbose_name_plural': 'FaqCatTitles2',
            },
        ),
    ]
