# Generated by Django 4.1.1 on 2022-09-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_faqcat1_faqcat2_alter_faqcatsubcat1_faqcat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqPostTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='FaqPostTitle title')),
            ],
            options={
                'verbose_name': 'FaqPostTitle',
                'verbose_name_plural': 'FaqPostTitles',
            },
        ),
    ]
