# Generated by Django 4.1.1 on 2022-09-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_faqposttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='FaqPost about')),
                ('img', models.ImageField(upload_to='media', verbose_name='FaqPost image')),
            ],
            options={
                'verbose_name': 'FaqPost',
                'verbose_name_plural': 'FaqPosts',
            },
        ),
    ]
