# Generated by Django 4.1.1 on 2022-09-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_pricingbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='PricingTitle title1')),
                ('title2', models.CharField(max_length=50, verbose_name='PricingTitle title2')),
            ],
            options={
                'verbose_name': 'PricingTitle',
                'verbose_name_plural': 'PricingTitles',
            },
        ),
    ]
